name: Merge ballerina bot pull requests.

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Create Automated VM Version Bump PR'

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - # It is often a desired behavior to merge only when a workflow execution
        # succeeds. This can be changed as needed.
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Merge me!
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: ballerina-bot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
