name: Relase Pack Test
on:
  workflow_dispatch:
    inputs:
      zipURL:
        description: 'Ballerina Zip Distribution URL'
        required: false
jobs:
  h1_h1_passthrough:
    name: h1_h1_passthrough
    runs-on: ubuntu-latest
    steps:
    - name: Trigger h1_h1_passthrough
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: anuruddhal
        repo: ballerina-performance-cloud
        github_token: ${{ secrets.BALLERINA_BOT_TOKEN }}
        workflow_file_name: test_hello.yml
        ref: main
        inputs: '{"zipURL":"http://dist-dev.ballerina.io/downloads/swan-lake-beta3/ballerina-swan-lake-beta3.zip"}'
        waiting_interval: 600
        trigger_workflow: true
        wait_workflow: true
