name: Relase Pack Test
on:
  workflow_dispatch:
    inputs:
      zipURL:
        description: 'Ballerina Zip Distribution URL'
        required: false
jobs:
  h1_h1_passthrough:
    name: h1_h1_passthrough
    runs-on: ubuntu-latest
    steps:
    - name: Trigger h1_h1_passthrough
      uses: felixp8/dispatch-and-wait@v0.1.0
      with:
        owner: anuruddhal
        repo: ballerina-performance-cloud
        token: ${{ secrets.BALLERINA_BOT_TOKEN }}
        event_type: test_hello
        client_payload: '{"zipURL":"${{github.event.inputs.zipURL}}"}'
        wait_time: 60
        max_time: 180