name: Relase Pack Test
on:
  workflow_dispatch:
    inputs:
      zipURL:
        description: 'Ballerina Zip Distribution URL'
        required: false
jobs:
  release_test:
    name: test_workflow
    runs-on: ubuntu-latest
    steps:
    - name: Trigger test workflow
      uses: felixp8/dispatch-and-wait@v0.1.0
      with:
        owner: anuruddhal
        repo: ballerina-performance-cloud
        token: ${{ secrets.BALLERINA_BOT_TOKEN }}
        event_type: test_hello
        client_payload: '{"zipURL":"${{github.event.inputs.zipURL}}"}'
        wait_time: 5
        max_time: 2400